dist: trusty
sudo: required
services:
  - docker
language: go
go:
  - "1.13.1"

before_install:
  - go get -t -v ./...
  - go get github.com/fzipp/gocyclo

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
  - go mod verify
  - GOOS=linux go build
  - go vet ./...                             # go vet is the official Go static analyzer
  - gocyclo -over 19 $GO_FILES               # forbid code with huge functions

after_success:
  - bash <(curl -s https://codecov.io/bash)
