dist: trusty
sudo: required
services:
  - docker
language: go
go:
  - "1.13.1"

before_install:
  - go get -t -v ./...
  - go get github.com/golang/lint/golint                        # Linter
  - go get honnef.co/go/tools/cmd/megacheck                     # Badass static analyzer/linter
  - go get github.com/fzipp/gocyclo

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
  - go mod verify
  - GOOS=linux go build
   - go vet ./...                             # go vet is the official Go static analyzer
  - megacheck ./...                          # "go vet on steroids" + linter
  - gocyclo -over 19 $GO_FILES               # forbid code with huge functions
  - golint -set_exit_status $(go list ./...) # one last linter

after_success:
  - bash <(curl -s https://codecov.io/bash)
